language: node_js
node_js:
- '0.10'
deploy:
  provider: divshot
  api_key:
    secure: NZKI8xbZ2FWTMsdrdybwpTP1zzyQbfE9RLWLPuDfpzBPPKxBLaBRx9DamOKlwBkQOmwpeK/zH4cwj+c0HwmKOWiKV/ZJdL2G5krSCZYP06oyfuoLIUNI/AcN8lrJoInqMP2RKc3evBfcsatqfk3wSeNLNvSzqnjrNLOrx25VszalqtDdtzEzqGaxQ226+qFIp5rCRKmss/Y8uX9952RfY6EtabpKnMfuyDUObMChE12DfmyLzHeMeFgmYKstrmgbGLaNCltu1g5HmphlSG8mCfaXTnQAJy5I4S7dn2h+LZZS+G9UfUhE/HVdbrk1paqBTmqZWvTtOUWJyWEBDcqymL6ow7jURK7S5WTlVyKtp66d0IKaY3Ay3aggrG27oyELXSKNYN+vLFDHOXNjG9Uwlfld9HiytlBjeMQhzv2EMCHVQVxrspxLwnWkd6STzvbHqoVXVhPJklludwwfFNW2LsMAo3mZvlhzXKbbJmQw9ML1uZVvVxp/IhZ4lOX/CFsPmORADFlxToxVzxckYCqDlHWiBuLgAMPQRFTu1vghE5Hd65QvrAoPvaWx3PuaRrsMDU/UgJfoB98hSFZdguJNJa3QIEJrvTtBhgwYHZyj0Pb227VsiYbzgQoqoPmsvaA2Qnxr+lN3sENMjWftElBzp408mo+Fg58AkYwZ/eDREyw=
  environment: production
  on:
    repo: travis-ci/travis-styleguide
